"""Generate src/generated.h from the sheets. Each row becomes one piece of code:
natives -> typed wrapper, game_hooks -> PatternDef, weapon -> GunDef, controls -> ControlDef.
Run tools/preflight.py first; this script refuses to run if it fails.

usage: python3 -I tools/gen.py
"""
import json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
S = lambda n: json.loads((ROOT / "sheets" / f"{n}.json").read_text())

CTYPE = {"Ped": "Ped", "Player": "Player", "Entity": "Entity", "Vehicle": "Vehicle", "Hash": "Hash",
         "BOOL": "BOOL", "int": "int", "float": "float", "const char*": "const char*",
         "Vehicle*": "Vehicle*", "Entity*": "Entity*", "Vector3": "Vector3", "void": "void"}

def ident(name):
    return name.lstrip("_")

def cstr(s):
    return json.dumps(s)

def f(x):
    s = repr(float(x))
    return s + "f"

def main():
    r = subprocess.run([sys.executable, "-I", str(ROOT / "tools" / "preflight.py")] + sys.argv[1:], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout)
        sys.exit("preflight failed: fix the sheets first")
    out = ["// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.",
           "#pragma once", "#include \"invoke.h\"", ""]

    out.append("namespace natives {")
    for n in S("natives")["rows"]:
        params = ", ".join(f"{CTYPE[t]} a{i}" for i, t in enumerate(n["args"]))
        call_args = "".join(f", a{i}" for i in range(len(n["args"])))
        ret = CTYPE[n["returns"]]
        out.append(f"// {n['usedFor']}")
        out.append(f"inline {ret} {ident(n['name'])}({params}) {{ return invoke<{ret}, {n['hash']}ULL>(\"{n['name']}\"{call_args}); }}")
    out.append("}  // namespace natives\n")

    out.append("enum class Resolve { Direct, Rip, RipImm8, Call };")
    out.append("struct PatternDef { const char* id; const char* pattern; Resolve resolve; int ripOffset; };")
    rmap = {"direct": "Resolve::Direct", "rip": "Resolve::Rip", "rip_imm8": "Resolve::RipImm8", "call": "Resolve::Call"}
    out.append("namespace hooks {")
    for i, h in enumerate(S("game_hooks")["rows"]):
        out.append(f"constexpr int {h['id']} = {i};  // {h['role']}")
    out.append("}")
    out.append("constexpr PatternDef kPatterns[] = {")
    for h in S("game_hooks")["rows"]:
        out.append(f"    {{{cstr(h['id'])}, {cstr(h['pattern'])}, {rmap[h['resolve']]}, {h['ripOffset']}}},")
    out.append("};\n")

    out.append("struct ControlDef { const char* name; bool isKey; uint32_t code; int pad; };")
    out.append("namespace controls {")
    for c in S("controls")["rows"]:
        out.append(f"constexpr ControlDef {c['id']} = {{{cstr(c['name'])}, {'true' if c['kind']=='key' else 'false'}, {c['code']}u, {c['padIndex']}}};  // {c['mode']}, {c['usedBy']}")
    out.append("}\n")

    out.append("struct GunDef {")
    out.append("    const char* id; const char* displayName; const char* propModel;")
    out.append("    int stripWheels[4]; int stripWheelCount;")
    out.append("    const char* holdMethod; const char* holdBone; float holdOffset[3]; float holdRot[3]; int stageDelayFrames;")
    out.append("    const char* muzzleBone; float muzzleFallbackOffset[3];")
    out.append("    const char* bulletWeapon; const char* bulletWeaponFallback; int damagePerBullet;")
    out.append("    int spinUpMs; int fireIntervalStartMs; int fireIntervalMinMs;")
    out.append("    float range; float bulletSpeed; float spreadDeg; const char* muzzleFx; bool infiniteAmmo;")
    out.append("    const char* holdAnimDict; const char* holdAnimName; int holdAnimFlags;")
    out.append("};")
    out.append("namespace guns {")
    for g in S("weapon")["rows"]:
        w = g["stripWheels"] + [0] * (4 - len(g["stripWheels"]))
        v3 = lambda a: "{" + ", ".join(f(x) for x in a) + "}"
        out.append(f"constexpr GunDef {g['id']} = {{")
        out.append(f"    {cstr(g['id'])}, {cstr(g['displayName'])}, {cstr(g['propModel'])},")
        out.append(f"    {{{', '.join(map(str, w))}}}, {len(g['stripWheels'])},")
        out.append(f"    {cstr(g['holdMethod'])}, {cstr(g['holdBone'])}, {v3(g['holdOffset'])}, {v3(g['holdRot'])}, {g['stageDelayFrames']},")
        out.append(f"    {cstr(g['muzzleBone'])}, {v3(g['muzzleFallbackOffset'])},")
        out.append(f"    {cstr(g['bulletWeapon'])}, {cstr(g['bulletWeaponFallback'])}, {g['damagePerBullet']},")
        out.append(f"    {g['spinUpMs']}, {g['fireIntervalStartMs']}, {g['fireIntervalMinMs']},")
        out.append(f"    {f(g['range'])}, {f(g['bulletSpeed'])}, {f(g['spreadDeg'])}, {cstr(g['muzzleFx'])}, {'true' if g['infiniteAmmo'] else 'false'},")
        out.append(f"    {cstr(g['holdAnimDict'])}, {cstr(g['holdAnimName'])}, {g['holdAnimFlags']},")
        out.append("};")
    out.append("}")
    (ROOT / "src" / "generated.h").write_text("\n".join(out) + "\n")
    print("wrote src/generated.h")

if __name__ == "__main__":
    main()
