// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.
#pragma once
#include "invoke.h"

namespace natives {
// find Arthur
inline Ped PLAYER_PED_ID() { return invoke<Ped, 0x096275889B8E0EE0ULL>("PLAYER_PED_ID"); }
// sanity check of hashing at start
inline Hash GET_HASH_KEY(const char* a0) { return invoke<Hash, 0xFD340785ADF8CFB7ULL>("GET_HASH_KEY", a0); }
// online guard
inline BOOL NETWORK_IS_SESSION_STARTED() { return invoke<BOOL, 0x9DE624D2FC4B603FULL>("NETWORK_IS_SESSION_STARTED"); }
// online guard
inline BOOL NETWORK_IS_GAME_IN_PROGRESS() { return invoke<BOOL, 0x10FAB35428CCC9D7ULL>("NETWORK_IS_GAME_IN_PROGRESS"); }
// ignore F7 in menus
inline BOOL IS_PAUSE_MENU_ACTIVE() { return invoke<BOOL, 0x535384D6067BA42EULL>("IS_PAUSE_MENU_ACTIVE"); }
// fire timing
inline int GET_GAME_TIMER() { return invoke<int, 0x4F67E8ECA7D3F667ULL>("GET_GAME_TIMER"); }
// prop bookkeeping
inline BOOL DOES_ENTITY_EXIST(Entity a0) { return invoke<BOOL, 0xD42BD6EB2E0F1677ULL>("DOES_ENTITY_EXIST", a0); }
// auto put-away
inline BOOL IS_ENTITY_DEAD(Entity a0) { return invoke<BOOL, 0x7D5B1F88E7504BBAULL>("IS_ENTITY_DEAD", a0); }
// auto put-away
inline BOOL IS_PED_ON_MOUNT(Ped a0) { return invoke<BOOL, 0x460BC76A0E10655EULL>("IS_PED_ON_MOUNT", a0); }
// auto put-away
inline BOOL IS_PED_IN_ANY_VEHICLE(Ped a0, BOOL a1) { return invoke<BOOL, 0x997ABD671D25CA0BULL>("IS_PED_IN_ANY_VEHICLE", a0, a1); }
// auto put-away
inline BOOL IS_PED_SWIMMING(Ped a0) { return invoke<BOOL, 0x9DE327631295B4C2ULL>("IS_PED_SWIMMING", a0); }
// pause firing
inline BOOL IS_PED_RAGDOLL(Ped a0) { return invoke<BOOL, 0x47E4E977581C5B55ULL>("IS_PED_RAGDOLL", a0); }
// load Gatling model
inline void REQUEST_MODEL(Hash a0, BOOL a1) { return invoke<void, 0xFA28FE3A6246FC30ULL>("REQUEST_MODEL", a0, a1); }
// load Gatling model
inline BOOL HAS_MODEL_LOADED(Hash a0) { return invoke<BOOL, 0x1283B8B89DD5D1B6ULL>("HAS_MODEL_LOADED", a0); }
// load Gatling model
inline void SET_MODEL_AS_NO_LONGER_NEEDED(Hash a0) { return invoke<void, 0x4AD96EF928BD4F9AULL>("SET_MODEL_AS_NO_LONGER_NEEDED", a0); }
// spawn Gatling
inline Vehicle CREATE_VEHICLE(Hash a0, float a1, float a2, float a3, float a4, BOOL a5, BOOL a6, BOOL a7, BOOL a8) { return invoke<Vehicle, 0xAF35D0D2583051B0ULL>("CREATE_VEHICLE", a0, a1, a2, a3, a4, a5, a6, a7, a8); }
// put Gatling away
inline void DELETE_VEHICLE(Vehicle* a0) { return invoke<void, 0xE20A909D8C4A70F8ULL>("DELETE_VEHICLE", a0); }
// own the prop so it can be deleted
inline void SET_ENTITY_AS_MISSION_ENTITY(Entity a0, BOOL a1, BOOL a2) { return invoke<void, 0xDC19C288082E586EULL>("SET_ENTITY_AS_MISSION_ENTITY", a0, a1, a2); }
// prop does not push Arthur
inline void SET_ENTITY_COLLISION(Entity a0, BOOL a1, BOOL a2) { return invoke<void, 0xF66F820909453B8CULL>("SET_ENTITY_COLLISION", a0, a1, a2); }
// prop cannot be shot apart
inline void SET_ENTITY_INVINCIBLE(Entity a0, BOOL a1) { return invoke<void, 0xA5C38736C426FCB8ULL>("SET_ENTITY_INVINCIBLE", a0, a1); }
// strip carriage wheels
inline Entity BREAK_OFF_VEHICLE_WHEEL(Vehicle a0, int a1) { return invoke<Entity, 0xD4F5EFB55769D272ULL>("_BREAK_OFF_VEHICLE_WHEEL", a0, a1); }
// delete broken-off wheels
inline void DELETE_ENTITY(Entity* a0) { return invoke<void, 0x4CD38C78BD19A497ULL>("DELETE_ENTITY", a0); }
// hand bone + barrel bone
inline int GET_ENTITY_BONE_INDEX_BY_NAME(Entity a0, const char* a1) { return invoke<int, 0xBACA8FE9C76C124EULL>("GET_ENTITY_BONE_INDEX_BY_NAME", a0, a1); }
// muzzle position
inline Vector3 GET_WORLD_POSITION_OF_ENTITY_BONE(Entity a0, int a1) { return invoke<Vector3, 0x82CFA50E34681CA5ULL>("GET_WORLD_POSITION_OF_ENTITY_BONE", a0, a1); }
// muzzle fallback
inline Vector3 GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(Entity a0, float a1, float a2, float a3) { return invoke<Vector3, 0x1899F328B0E12848ULL>("GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS", a0, a1, a2, a3); }
// aim ray
inline Vector3 GET_FINAL_RENDERED_CAM_COORD() { return invoke<Vector3, 0x5352E025EC2B416FULL>("GET_FINAL_RENDERED_CAM_COORD"); }
// aim ray
inline Vector3 GET_FINAL_RENDERED_CAM_ROT(int a0) { return invoke<Vector3, 0x602685BD85DD26CAULL>("GET_FINAL_RENDERED_CAM_ROT", a0); }
// pick bullet type
inline BOOL IS_WEAPON_VALID(Hash a0) { return invoke<BOOL, 0x937C71165CF334B3ULL>("IS_WEAPON_VALID", a0); }
// the spray
inline void SHOOT_SINGLE_BULLET_BETWEEN_COORDS(float a0, float a1, float a2, float a3, float a4, float a5, int a6, BOOL a7, Hash a8, Ped a9, BOOL a10, BOOL a11, float a12, BOOL a13) { return invoke<void, 0x867654CBC7606F2CULL>("SHOOT_SINGLE_BULLET_BETWEEN_COORDS", a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13); }
// muzzle flash
inline BOOL START_PARTICLE_FX_NON_LOOPED_AT_COORD(const char* a0, float a1, float a2, float a3, float a4, float a5, float a6, float a7, BOOL a8, BOOL a9, BOOL a10) { return invoke<BOOL, 0x2E80BF72EF7C87ACULL>("START_PARTICLE_FX_NON_LOOPED_AT_COORD", a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); }
// read fire/aim
inline BOOL IS_CONTROL_PRESSED(int a0, Hash a1) { return invoke<BOOL, 0xF3A21BCD95725A4AULL>("IS_CONTROL_PRESSED", a0, a1); }
// read fire after disabling it for the game
inline BOOL IS_DISABLED_CONTROL_PRESSED(int a0, Hash a1) { return invoke<BOOL, 0xE2587F8CBBD87B1DULL>("IS_DISABLED_CONTROL_PRESSED", a0, a1); }
// sprint lock, block melee/normal firing
inline void DISABLE_CONTROL_ACTION(int a0, Hash a1, BOOL a2) { return invoke<void, 0xFE99B66D079CF6BCULL>("DISABLE_CONTROL_ACTION", a0, a1, a2); }
// hip-hold pose
inline void REQUEST_ANIM_DICT(const char* a0) { return invoke<void, 0xA862A2AD321F94B4ULL>("REQUEST_ANIM_DICT", a0); }
// hip-hold pose
inline BOOL HAS_ANIM_DICT_LOADED(const char* a0) { return invoke<BOOL, 0x27FF6FE8009B40CAULL>("HAS_ANIM_DICT_LOADED", a0); }
// hip-hold pose
inline void TASK_PLAY_ANIM(Ped a0, const char* a1, const char* a2, float a3, float a4, int a5, int a6, float a7, BOOL a8, int a9, BOOL a10, const char* a11, BOOL a12) { return invoke<void, 0xEA47FE3719165B94ULL>("TASK_PLAY_ANIM", a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); }
// re-apply pose if interrupted
inline BOOL IS_ENTITY_PLAYING_ANIM(Entity a0, const char* a1, const char* a2, int a3) { return invoke<BOOL, 0xDEE49D5CA6C49148ULL>("IS_ENTITY_PLAYING_ANIM", a0, a1, a2, a3); }
// drop pose on put-away
inline void STOP_ANIM_TASK(Ped a0, const char* a1, const char* a2, float a3) { return invoke<void, 0x97FF36A1D40EA00AULL>("STOP_ANIM_TASK", a0, a1, a2, a3); }
// holster Arthur's own gun while the Gatling is out
inline void SET_CURRENT_PED_WEAPON(Ped a0, Hash a1, BOOL a2, int a3, BOOL a4, BOOL a5) { return invoke<void, 0xADF692B254977C0CULL>("SET_CURRENT_PED_WEAPON", a0, a1, a2, a3, a4, a5); }
// Gatling faces where Arthur faces
inline float GET_ENTITY_HEADING(Entity a0) { return invoke<float, 0xC230DD956E2F5507ULL>("GET_ENTITY_HEADING", a0); }
// no physics on the held Gatling
inline void FREEZE_ENTITY_POSITION(Entity a0, BOOL a1) { return invoke<void, 0x7D9EFB7AD6B19754ULL>("FREEZE_ENTITY_POSITION", a0, a1); }
// move the Gatling to Arthur's hands each frame
inline void SET_ENTITY_COORDS_NO_OFFSET(Entity a0, float a1, float a2, float a3, BOOL a4, BOOL a5, BOOL a6) { return invoke<void, 0x239A3351AC1DA385ULL>("SET_ENTITY_COORDS_NO_OFFSET", a0, a1, a2, a3, a4, a5, a6); }
// turn the Gatling each frame
inline void SET_ENTITY_ROTATION(Entity a0, float a1, float a2, float a3, int a4, BOOL a5) { return invoke<void, 0x9CC8314DFEDE441EULL>("SET_ENTITY_ROTATION", a0, a1, a2, a3, a4, a5); }
// Arthur can't climb onto the Gatling he's holding
inline void SET_VEHICLE_DOORS_LOCKED(Vehicle a0, int a1) { return invoke<void, 0x96F78A6A075D55D9ULL>("SET_VEHICLE_DOORS_LOCKED", a0, a1); }
}  // namespace natives

enum class Resolve { Direct, Rip, RipImm8, Call };
struct PatternDef { const char* id; const char* pattern; Resolve resolve; int ripOffset; };
namespace hooks {
constexpr int getNativeAddress = 0;  // native hash -> handler address
constexpr int currentScriptThread = 1;  // pointer to the active script thread slot
constexpr int scriptHandlerManager = 2;  // registers our script thread with the game
constexpr int isInSession = 3;  // online flag; logged only (the online guard itself uses natives). rip_imm8 = cmp [rip+disp32],imm8 so the address is relative to the end of the 7-byte instruction
constexpr int updateSingleScripts = 4;  // detoured: ticks our script thread every frame
constexpr int shutdownLoadingScreen = 5;  // detoured: start only after the loading screen
constexpr int initScriptThread = 6;  // game's scrThread init
constexpr int tickScriptThread = 7;  // game's scrThread tick (calls our Run)
constexpr int sysAlloc = 8;  // game allocator for our thread object
}
constexpr PatternDef kPatterns[] = {
    {"getNativeAddress", "48 8B 15 ? ? ? ? 4C 8B C9 49 F7 D1", Resolve::Direct, 0},
    {"currentScriptThread", "48 39 1D ? ? ? ? 75 ? 48 8D 05 ? ? ? ?", Resolve::Rip, 3},
    {"scriptHandlerManager", "48 8D 0D ? ? ? ? E8 ? ? ? ? 84 C0 75 ? 8B 8B ? ? ? ?", Resolve::Rip, 3},
    {"isInSession", "80 3D ? ? ? ? ? 74 ? 48 8B 0D ? ? ? ? E8 ? ? ? ? 0F B6 40 ?", Resolve::RipImm8, 2},
    {"updateSingleScripts", "48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 41 56 41 57 48 83 EC ? 45 33 F6 BD ? ? ? ?", Resolve::Direct, 0},
    {"shutdownLoadingScreen", "8A 05 ? ? ? ? 84 C0 75 ? C6 05 ? ? ? ? ?", Resolve::Direct, 0},
    {"initScriptThread", "48 89 5C 24 ? 57 48 83 EC ? 83 89 ? ? ? ? ? 33 FF 83 A1", Resolve::Direct, 0},
    {"tickScriptThread", "48 89 5C 24 ? 57 48 83 EC ? 80 B9 ? ? ? ? ? 8B FA 48 8B D9 74 ? 8B 41", Resolve::Direct, 0},
    {"sysAlloc", "E8 ? ? ? ? 48 85 C0 74 ? 48 83 20 ? 0F 57 C0 0F 11 40 ? 0F 11 40 ? 83 60", Resolve::Call, 1},
};

struct ControlDef { const char* name; bool isKey; uint32_t code; int pad; };
namespace controls {
constexpr ControlDef toggle = {"F7", true, 0x76u, 0};  // edge, toggle
constexpr ControlDef fire = {"INPUT_ATTACK", false, 0x07CE1E61u, 0};  // read_disabled, fire
constexpr ControlDef aim = {"INPUT_AIM", false, 0xF84FA74Fu, 0};  // read, fire
constexpr ControlDef sprint = {"INPUT_SPRINT", false, 0x8FFC75D6u, 0};  // disable, sprint_lock
constexpr ControlDef melee = {"INPUT_MELEE_ATTACK", false, 0xB2F377E8u, 0};  // disable, fire
constexpr ControlDef attack_block = {"INPUT_ATTACK", false, 0x07CE1E61u, 0};  // disable, fire
}

struct GunDef {
    const char* id; const char* displayName; const char* propModel;
    int stripWheels[4]; int stripWheelCount;
    const char* holdMethod; const char* holdBone; float holdOffset[3]; float holdRot[3]; int stageDelayFrames;
    const char* muzzleBone; float muzzleFallbackOffset[3];
    const char* bulletWeapon; const char* bulletWeaponFallback; int damagePerBullet;
    int spinUpMs; int fireIntervalStartMs; int fireIntervalMinMs;
    float range; float bulletSpeed; float spreadDeg; const char* muzzleFx; bool infiniteAmmo;
    const char* holdAnimDict; const char* holdAnimName; int holdAnimFlags;
};
namespace guns {
constexpr GunDef arthur_gatling = {
    "arthur_gatling", "Arthur's Gatling", "gatling_gun",
    {0, 1, 0, 0}, 2,
    "follow", "PH_R_Hand", {0.0f, 0.35f, -0.1f}, {0.0f, 0.0f, 0.0f}, 15,
    "weapon_1a", {0.0f, 1.2f, 0.0f},
    "WEAPON_TURRET_GATLING", "WEAPON_REPEATER_CARBINE", 35,
    900, 160, 55,
    150.0f, -1.0f, 1.6f, "muz_gatling", true,
    "mech_carry_box", "idle", 49,
};
}
